name: Call Crux API

on: [workflow_dispatch]

jobs:
  call_crux_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Call CruX API and log response
        id: crux-api
        env:
          CRUX_KEY: ${{ secrets.CRUXKEY }}
        run: 
          cruxResponse=$(node index.js)
          echo $cruxResponse
          echo "CRUX_OUTPUT=$cruxResponse" >> $GITHUB_ENV
          
      - name: Use API response in the next step
        run: 
          scriptOutput="${{ env.CRUX_OUTPUT }}"
          echo "The output from index.js is $scriptOutput"

#         echo "The API originOrUrl is ${{ steps.api.outputs.originOrUrl }}" 
#         echo "The API largest_contentful_paint is ${{ steps.api.outputs.largest_contentful_paint }}"
